# Generated by Django 6.0.5 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_party_historical_context_party_crime_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='historical_context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
